data <- read.table("./household_power_consumption.txt",header=TRUE,sep=";")
data <- subset(data,data$Date=="1/2/2007" | data$Date=="2/2/2007")
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)

data$datetime <- strptime(paste(data$Date, data$Time, sep = ""), "%d/%m/%Y %H:%M:%S")

png("plot3.png", width=480, height=480)
par(mfrow = c(1,1))
plot(data$datetime, data$Sub_metering_1, type="l", xlab="", ylab="Energy Submetering")
lines(data$datetime, data$Sub_metering_2,type="l",col="red")
lines(data$datetime, data$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2, col=c("black", "red", "blue"))
dev.off()